FROM ruby:3.3-slim

RUN apt-get update && apt-get install -y --no-install-recommends ffmpeg build-essential && rm -rf /var/lib/apt/lists/*

COPY . /app
WORKDIR /app
RUN bundle install --with web

EXPOSE 4567

CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]
